- name: Render frontend .env
  template:
    src: frontend_env.j2
    dest: "{{ frontend_dir }}/.env"
    mode: '0644'

- name: Install frontend dependencies
  command: "{{ node_command }} install"
  args:
    chdir: "{{ frontend_dir }}"

- name: Build frontend
  command: "{{ node_command }} run build"
  args:
    chdir: "{{ frontend_dir }}"
